const profiles={
    george:'South Asian man in his late twenties with a structured jawline, deep-set warm hazel-brown eyes, a well-groomed dark full beard and mustache, and thick, voluminous jet-black curly hair. He wears a dark navy casual jacket over a subtle light patterned button-down shirt, slim-fit black denim jeans, and brown leather casual sneakers.',
    sarah:'South Asian young adult woman in her early twenties with a soft oval face, large dark brown eyes, soft pink blush and matte pink lipstick. Her dark hair forms a braided crown flowing into a voluminous low bun at the nape, decorated with clusters of pink and white miniature roses and soft face-framing curls. She wears a plain solid magenta scoop-neck top and traditional gold jhumka earrings with pink stones. No veil, necklace or bangles. Match the approved Sarah reference face, hairstyle, top and earrings. Frame Sarah from the waist up or closer; do not invent or show a lower outfit. Her expression follows the dialogue naturally.'
};
function enabled(p){return ['relationship-dialogue-real','relationship-dialogue-ghibli'].includes(p.id) && p.fixed_couple_appearance;}
function description(p,name){const text=enabled(p)&&p.fixed_couple_appearance[name.toLowerCase()];const medium=p.id==='relationship-dialogue-ghibli'?'Hand-painted 2D Japanese animated-film character, clean ink line art, gentle cel shading and soft watercolour texture. Preserve the reference facial identity and adult proportions; no photorealistic rendering.':'Photorealistic human, natural skin and fabric texture.';return text?`Same ${name} throughout - ${text} ${medium} Expression follows the conversation; a joyful reference smile is not a permanent expression.`:null;}
function sheet(p,name){const d=description(p,name);const views=name.toLowerCase()==='sarah'?'waist-up front, three-quarter, side and rear views plus a face close-up; no lower-body views':'front, three-quarter, side and rear full-body views plus a face close-up';return d?`${d} One reference sheet, same person and outfit in ${views}. Plain light background, clear natural lighting. No text or watermark.`:null;}
function apply(p,cast){return cast.map(c=>description(p,c.name)?{...c,description:description(p,c.name),sheet_prompt:sheet(p,c.name)}:c);}
function prompt(p){return enabled(p)?'APPROVED CHARACTER APPEARANCES (override generic templates and source appearances; render in the selected preset medium):\n'+Object.entries(p.fixed_couple_appearance).map(([n,d])=>`${n}: ${d}`).join('\n')+'\nKeep the exact outfit; expressions follow dialogue, not a permanent smile.':'';}
module.exports={profiles,enabled,description,sheet,apply,prompt};
