const assert=require('assert');
const del=require('../delete_project_video_clips');
let videoClicks=0,imageClicks=0;
const videoButton={disabled:false,getAttribute:()=> 'Trash batch',click:()=>videoClicks++};
const imageButton={disabled:false,getAttribute:()=> 'Trash batch',click:()=>imageClicks++};
const image={querySelectorAll:()=>[imageButton]};
const row={parentElement:null,querySelectorAll:s=>s==='button'?[videoButton]:[]};
const tile={parentElement:row,closest:()=>null,querySelectorAll:()=>[]};
global.window={__singleOmniTileKeys:{keys:new WeakMap([[tile,'video']])}};
global.document={querySelectorAll:s=>s==='flow-video-tile'?[tile]:[image]};
assert(del.clickVideoTrash({key:'video'}));assert.equal(videoClicks,1);assert.equal(imageClicks,0);
assert(!del.clickVideoTrash({key:'image'}));assert.equal(imageClicks,0);
const menuButton={disabled:false,getAttribute:()=> 'More options',click:()=>videoClicks++};
row.querySelectorAll=s=>s==='button'?[menuButton]:[];
assert.equal(del.clickVideoTrash({key:'video'}),'menu');assert.equal(videoClicks,2);
tile.closest=()=>({});assert(!del.clickVideoTrash({key:'video'}));assert.equal(videoClicks,2);
let menuTrashClicks=0,downloadClicks=0;
const item=label=>({disabled:false,getBoundingClientRect:()=>({width:200,height:40}),querySelector:()=>({textContent:label}),getAttribute:()=>null,innerText:'delete '+label,click:()=>{if(label==='Move to trash')menuTrashClicks++;else downloadClicks++;}});
document.querySelectorAll=()=>[item('Download'),item('Move to trash')];
assert(del.clickTrashMenuItem());assert.equal(menuTrashClicks,1);assert.equal(downloadClicks,0);
document.querySelectorAll=()=>[item('Move to trash'),item('Move to trash')];assert.throws(()=>del.clickTrashMenuItem(),/More than one/);assert.equal(menuTrashClicks,1);
delete global.window;delete global.document;
(async()=>{
 let checks=0,opened=0;
 const page={evaluate:async(fn)=>{if(fn.name==='clickVideoTrash'){opened++;return 'menu';}if(fn.name==='clickTrashMenuItem')return ++checks===2;}};
 assert.equal(await del.moveVideoToTrash(page,{key:'video'},{wait:async()=>{}}),'menu');assert.equal(opened,1);assert.equal(checks,2);
 await assert.rejects(del.run({project:'https://flow.google.com/project/example',confirmed:false}),/confirmation/);
 console.log('PASS: direct and menu video trash routes, exact nested Move to trash label, no Download/image action, menu wait and explicit confirmation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
