const assert=require('assert');
const fs=require('fs');
const camera=require('../fantasy_advice_camera');
const {ingredientsCameraPrompt}=require('../ingredients_camera');
const s={niche:'Fantasy Princess — Relationship Advice',style:'Fantasy',character_descriptions:{liora:'Woman',pip:'Frog'},place:{description:'Garden'},scenes:Array.from({length:4},()=>({dialogue:[{speaker:'Liora',line:'Keep your promises.'}],veo3_prompt:'[SHOT] Old walking action\n[LOOK] Fantasy\n[AUDIO] Liora says: Keep your promises.'}))};
const dialogue=JSON.stringify(s.scenes.map(x=>x.dialogue));camera.apply(s);
assert.equal(dialogue,JSON.stringify(s.scenes.map(x=>x.dialogue)));
assert(s.scenes[0].narrative_context.includes('ONE smooth zoom'));
assert(s.scenes.slice(1).every(x=>x.narrative_context.includes('already seated')));
assert(s.scenes[2].narrative_context.includes('identical chest-up crop established at the end of clip 1'));
assert(s.scenes[1].narrative_context.includes('little headroom'));
assert(s.scenes.slice(1).every(x=>x.narrative_context.includes('Her waist, hands, lap, skirt, legs and bench are outside the frame')));
assert(s.scenes.slice(1).every(x=>!x.narrative_context.includes('most of her seated skirt')));
for(const scene of s.scenes)assert.equal(ingredientsCameraPrompt(s,scene,scene.veo3_prompt),scene.veo3_prompt);
assert(s.scenes[0].veo3_prompt.includes('hop onto her right shoulder'));
assert(s.scenes[1].veo3_prompt.includes('hop to her left shoulder'));
assert(s.scenes[2].veo3_prompt.includes('hop to her right shoulder'));
assert(s.scenes.every(x=>!x.veo3_prompt.includes('Pip stays quietly beside her off-camera')));
const file='stories/a_peaceful_home_begins_with_the_promises_we_keep/a_peaceful_home_begins_with_the_promises_we_keep_story.json';
const actual=JSON.parse(fs.readFileSync(file));assert.equal(actual.scenes.length,4);
console.log('PASS: walk and sit in clip 1; tight fixed seated crop from clip 2; dialogue preserved; Ingredients camera cannot override fantasy direction.');
